OutputDir: !!python/object/apply:pathlib.PosixPath
- /
- home
- nsm
- Desktop
- All_Development
- Sars-cov-analysis
- tool
- tool
- media
- 000-000-000
UpdateDir: !!python/object/apply:pathlib.PosixPath
- /
- home
- nsm
- Desktop
- All_Development
- Sars-cov-analysis
- tool
- tool
- workflow
Date: 19-07-2022